### ISSUE TITLE
[BUG] Chat Widget mobile view in eesti.ee web application is not responsive

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Chat-Widget#319]
> [!IMPORTANT]
> BUG when viewing Chat Widget in mobile view
> See screenshot in comments

### Acceptance Criteria

- [ ] Chat Widget is responsive in eesti.ee web application
- [ ] Messages will be forwarded to the backoffice when they are ended
- [ ] End user can close the chat and leave feedback

**Comment by turnerrainer** [comment]
![Image](https://github.com/user-attachments/assets/08757696-3c86-4a51-bdd2-65c0ab9e103d)

**Comment by 1AhmedYasser** [comment]
https://github.com/user-attachments/assets/efeb408d-78e2-4d03-8b41-d9db1decf1f3


Seems like a UI Issue on the app side, it needs to be fixed from the app side, i can guide if needed

**Comment by rasmusei** [comment]
Will be solved from app side
