### ISSUE TITLE
[BUG] Possibility to authenticate as an End User in the widget visible

### ISSUE THREAD

**Issue by rasmusei** [buerokratt/Chat-Widget#330]
**Bug description:** In some cases End Users can authenticate themselves in the widget right from the start. This was reported by PPA. Not sure how to reproduce this.

**Expected behavior:** In the chat widget it should not be possible to authenticate yourself as an End User, this option should not be available

**Screenshots:** ![Image](https://github.com/user-attachments/assets/50363ab8-7893-4183-bebb-67781573b87e)

**Additional information:** If anything found and solved please let Anna from PPA know

**Comment by jaX10bt** [comment]
It seems that the `authenticateWithTara` button is visible anytime the end user is not authenticated and that the chat has a chatId.

https://github.com/buerokratt/Chat-Widget/blob/a1661f2c15559c7491caf1cfddf15be2992dd632/src/components/chat-header/widget-details.tsx#L22

**Comment by ExiRain** [comment]
Removed Auth button
[Pull request](https://github.com/buerokratt/Chat-Widget/pull/331).

**Comment by jaX10bt** [comment]
Works as intended
